import Layout from './components/layout/Layout'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
     <Layout>
   {/* // <html lang="en"> */}
     
      <body >{children}</body>
     
   {/* // </html> */}
     </Layout>
  )
}
